### ISSUE TITLE
Error 'Uncaught Error: spawn pandoc ENOENT'

### ISSUE THREAD

**Issue by twsh** [jagregory/atom-pandoc-preview#14]
Whenever I try to preview I get the error 'Uncaught Error: spawn pandoc ENOENT'. I'm using version 0.1.2, Atom version 0.165.0 on OS X.

Here is the stack trace:

```
Error: spawn pandoc ENOENT
  at exports._errnoException (util.js:742:11)
  at Process.ChildProcess._handle.onexit (child_process.js:1051:32)
  at child_process.js:1142:20
  at process._tickCallback (node.js:378:11)
```

**Comment by Skyfold** [comment]
I had the same problem, with the same error message as above. To fix it you have to:

```
 vi `which atom`
```
Add "env" before this line:
```
open -a "$ATOM_PATH/$ATOM_APP_NAME" -n --args --executed-from="$(pwd)" --pid=$$ --path-environment="$PATH" "$@"
```
Like so:
```
env open -a "$ATOM_PATH/$ATOM_APP_NAME" -n --args --executed-from="$(pwd)" --pid=$$ --path-environment="$PATH" "$@"
```
__Then call atom from the command line.__ I have yet to make it work by calling atom from spotlight

I also tried editing /etc/launchd.conf, adding in `setenv PATH /Applications/Atom.app` to the file and reloading everything with `grep -E "^setenv" /etc/launchd.conf | xargs -t -L 1 launchctl`, but that only gave me this error instead:

`'pandoc' could not be spawned. Is it installed and on your path? If so please open an issue on the package spawning the process.`

**Comment by jeffmcneill** [comment]
I've got the same issue. Will work when I run atom from command line, but not launch as an icon/explorer. I've added "env" and that didn't fix it. Any updates of things to try out?

**Comment by jagregory** [comment]
I'm afraid not. This is a more general issue with Atom (and Sublime) and Macs, unfortunately.

**Comment by maxheld83** [comment]
I have the same problem, on OS X – even though `PATH` is set up as indicated:

```
open -a "$ATOM_PATH/$ATOM_APP_NAME" -n --args --executed-from="$(pwd)" --pid=$$ --path-environment="$PATH" "$@"
```

Starting Atom from CLI works just fine, oddly.
