### ISSUE TITLE
Doesn't recognize UTF8 in preview

### ISSUE THREAD

**Issue by retrography** [jagregory/atom-pandoc-preview#17]
It displays UTF-8 texts as ISO Western, which results in the following:

![screen shot 2015-01-10 at 7 11 24 pm](https://cloud.githubusercontent.com/assets/5309061/5693794/81b6f092-98fc-11e4-842a-76c7a2588dd4.png)

The html generated using the same switches displays fine in Chrome or Safari.

**Comment by jagregory** [comment]
I'm guessing this is a Atom node-webkit issue we don't have much control over. We're just embedding HTML in Atom.

**Comment by retrography** [comment]
I verified and this is actually a limitation inherent to bibtex. Just FYI...

**Comment by monoblaine** [comment]
@retrography 

In `pandoc-view.coffee`, change the `frame` property as follows:

~~~
frame: (html) ->
    @html $$$ ->
      @iframe src: "data:text/html;charset=utf-8, #{encodeURI html}"
~~~

You might also need to remove `--ascii` from `args` in `pandoc.coffee`.

**Comment by retrography** [comment]
@monoblaine Interesting. Thanks. I will try it.
