### ISSUE TITLE
Object.Object.defineProperty.get is deprecated.

### ISSUE THREAD

**Issue by shotlom** [jagregory/atom-pandoc-preview#18]
Requiring `View` from `atom` is no longer supported.
Please require `atom-space-pen-views` instead:
  `{View} = require 'atom-space-pen-views'`
Add `"atom-space-pen-views": "^2.0.3"` to your package dependencies.
```
Object.Object.defineProperty.get (/Applications/Atom.app/Contents/Resources/app.asar/exports/atom.js:66:11)
Object.<anonymous> (/Users/chr/.atom/packages/pandoc/lib/pandoc-view.coffee:2:9)
Object.<anonymous> (/Users/chr/.atom/packages/pandoc/lib/pandoc-view.coffee:104:4)
Module._compile (module.js:452:26)
```

**Comment by jagregory** [comment]
Could you send me a pull request please as you seem to know exactly what needs changing already. :smile:

**Comment by shotlom** [comment]
Ha! No - this was automatically generated by Atom and it said "do you want to create a Git issue"? So I said yeah, sure why not.

**Comment by jagregory** [comment]
New release pushed, fixing these deprecations. Update the Pandoc package from within Atom and these warnings should go away. Thanks.
