### ISSUE TITLE
Can't configure settings with Atom 1.0

### ISSUE THREAD

**Issue by Wind4Greg** [jagregory/atom-pandoc-preview#23]
With Atom 1.0 (on Windows) no *settings pane* or other mechanism shows up on the GUI to configure the `pandoc.cm`, `pandoc.args`, or `pandoc.languages` settings.
Don't know if this was a breaking change with Atom 1.0.
Would very much like to use this plugin but can't get it configured.
Thanks
Greg B.

**Comment by jagregory** [comment]
I don't know if the settings were ever exposed in the configuration.

You can just edit the Atom config. There'll be an `Open Your Config` menu item somewhere.

**Comment by Wind4Greg** [comment]
Tried editing the `config.cson` file as follows but still get the an exception thrown when trying to run it.
```
pandoc:
    "pandoc.cmd": "pandoc.exe"
```

**Comment by jagregory** [comment]
I've just pushed a new version, which should fix both your crash and the settings not being available to edit. Please install v0.2.2 from Atom.

**Comment by Wind4Greg** [comment]
Just downloaded v0.2.2. Worked like a charm! 
Thanks
