### ISSUE TITLE
Annoying Problems About hexo -s、-g 

### ISSUE THREAD

**Issue by HydrogenSulfate** [jagregory/atom-pandoc-preview#34]
These days I refered to the Other master's guidance to Build my hexo blog，but there always exits a problem, that when I execute "hexo s", cmd window is easily to show that error
![image](https://user-images.githubusercontent.com/23737287/30682627-e449aed2-9edc-11e7-8408-869130c29094.png)，
![image](https://user-images.githubusercontent.com/23737287/30682777-6e601aca-9edd-11e7-98cd-0f213e6e0787.png)
and so as hexo -g，At the beginning I feel excited and glad to build my own blog ,but that error disturbs me and take my most time to looking for a solution, is there anyone could give some solution or even you may have countered that problem before like that....So thankful to u

**Comment by jagregory** [comment]
I think you probably want: https://github.com/hexojs/hexo or https://github.com/jgm/pandoc
